### ISSUE TITLE
屋号を決める

### ISSUE THREAD

**Issue by tyore2** [tyore2/newproject#1]
- 【共通項】春生まれ
- 【表に出す指針】よいものを伝える
- 【内側にひめたルール】ちゃんと息をする、自由ということに責任をもつ、やりたいことをやる

**Comment by mohariyoshi2** [comment]
何を目指したいかというと
 - やりたいことをやる
 - 「よいもの」を伝える
 -

**Comment by mohariyoshi2** [comment]
たくましくてかわいい生き物とかいないかな〜

**Comment by tyore2** [comment]
ちゃんと息する、自由に責任をもつ、すごくいい〜  

## たくましてかわいい生き物をただ羅列してみる
むずかしいぞこれw
- ライオンの赤ちゃん
- とかげ（しっぽ切ってものびてくる）
- 鮭（かわいくはない）
- クマ
- 雑草の花

**Comment by mohariyoshi2** [comment]
雑草の花、よいかもしれない。

春の雑草の花。
なぜなら我々は春生まれのはるかだから！

**Comment by mohariyoshi2** [comment]
http://www.hana300.com/aazasso.html

初っ端がオオイヌノフグリで笑う

**Comment by mohariyoshi2** [comment]
何かモチーフを持ちつつ、
覚えてもらいやすい屋号をつけよう

**Comment by mohariyoshi2** [comment]
文字量wwwありがとうw

「プラナタス」かっこいー！と思ったけどビジュアルが地味目だなぁ
「ネモフィラ」ビジュアル良いし言葉も良い
「フロックス」は我々の境遇と似ていて興味深い、花は個人的には好みではない
「ラナンキュラス」は言葉よし、花よし（少し派手かな）
「ルピナス」も言葉よし、花それなり

**Comment by mohariyoshi2** [comment]
プラナタス 地味ではなかった
https://www.google.co.jp/search?biw=1250&bih=880&tbm=isch&sa=1&ei=abveWtXSBIOc0gTQ-JLADg&q=%E3%83%97%E3%83%A9%E3%82%BF%E3%83%8A%E3%82%B9+%E8%8A%B1+%E7%94%BB%E5%83%8F&oq=%E3%83%97%E3%83%A9%E3%83%8A%E3%82%BF%E3%82%B9+&gs_l=psy-ab.3.6.0i13k1l8.6866.6866.0.12016.1.1.0.0.0.0.87.87.1.1.0....0...1c.1.64.psy-ab..0.1.87....0.RjBg4OB1DPE

**Comment by tyore2** [comment]
花ってなんか派手だよねww（ピントくるものがあまりない）
もうちょっと落ち着いた何かもないか探してみよう

**Comment by tyore2** [comment]
# 春の季語
http://kigosai.sub.jp/%E6%98%A5%E3%81%AE%E5%AD%A3%E8%AA%9E
めっちゃある... 動物、植物あたりをみてみよう

**Comment by mohariyoshi2** [comment]
HARUKAT-TUN

**Comment by tyore2** [comment]
# 春の野菜
https://www.yasainavi.com/zukan/index/season=1
あしたば
アスパラガス
アーティチョーク
うど
からし菜
キャベツ
グリーンピース
クレソン
さやえんどう
じゃがいも
セロリ
そらまめ
たけのこ
玉ねぎ
なばな
にら
にんじん
にんにく
パセリ
ひらたけ
ふき
みずな
みつば
ルッコラ

**Comment by tyore2** [comment]
KAT-TUNwwww

**Comment by mohariyoshi2** [comment]
いっちばんビジュアルとして地味そうで誰もモチーフに選ばなそうなものを、
良い感じにできたら、とても良いのかも

アナグラムで英語以外だと、「はかる」とかだとそれっぽいね

**Comment by mohariyoshi2** [comment]
haruka2 とかね
ふたりともアカウントに2ついてるからw

**Comment by tyore2** [comment]
あ、haruka2でいいかもしれないwww 理由も明快（自分たちにとっては）

# ちなみに「はかる」
【計る・測る・量る・図る】
## 1.計・測・量
はかり・ます・物差しなどで、重さ・量・長さなどを知る操作をする。一般に、測定具で物の量を調べる。 「タイムを―」
## 2.計・測
こうもあろうかと、推して考える。推しはかる。推量する。予測する。 「真意が―・りかねる」
## 3.計・図
心をその事に向けて処置などを考える。相談する。議事とする。 「皆に―・って決める」
都合を考えてやる。配慮する。 「遠距離通勤者の便宜を―」
## 4.計・図
その事の実現を企てる。意図する。計画する。 「再起を―」
## 5.計
企ててだます。うまく引っ掛ける。

**Comment by mohariyoshi2** [comment]
「はかる」ちょっとカッコつけちゃってるかもね！

haruka2で「はるかに」と読み、
サルカニ合戦みたいな響で可愛い、まろやかで可愛い、
はるかがふたり、はるかが第二の仕事を... etc

名前を使うの照れる///

**Comment by mohariyoshi2** [comment]
カニをキャラクタにするのもかわいいかもw
ピースしてるし✌️

**Comment by tyore2** [comment]
はるかにのほうがたしかに言うのはずかしくないしかわいらしい。
haruka2 で決定でww

**Comment by tyore2** [comment]
🦀

**Comment by mohariyoshi2** [comment]
世間のかには冬だが、
http://woman-life.jp/kanishun.html

我々は春のかにということで

**Comment by tyore2** [comment]
# haruka2（はるかに）に決定
- はるかが２人→「haruka2」
- はるかの2つめの仕事
- 🦀 ピース
- ひびきがかわいい

**Comment by tyore2** [comment]
つづき → https://github.com/tyore2/newproject/issues/6
